#!/bin/bash -xe

REPO=`pwd`/../..

#rm -rf /home/ssarkar/wesnoth-android/wesnoth-aab-base

#for arch in "x86_64" "armeabi-v7a" "arm64-v8a" "x86"
for arch in "armeabi-v7a"
do
	mkdir -p /home/ssarkar/wesnoth-android/wesnoth-$arch
	pushd /home/ssarkar/wesnoth-android/wesnoth-$arch
		scons -j`nproc` -Y $REPO prefix=/home/ssarkar/wesnoth-android/android-prefix/$arch host=android-$arch ndkdir=/home/ssarkar/Android/android-ndk-r26d extra_flags_config=-lm autorevision=false android_api=23 android_home=/home/ssarkar/Android/Sdk/ apk
	popd
	mkdir -p /home/ssarkar/wesnoth-android/wesnoth-aab-base
	pushd /home/ssarkar/wesnoth-android/wesnoth-aab-base
		unzip -n /home/ssarkar/wesnoth-android/wesnoth-$arch/packaging/android/wesnoth-debug.apk
	popd
done
rm -f /home/ssarkar/Documents/Projects/C++/wesnoth/packaging/android/app/src/main/jniLibs/armeabi-v7a/libmain.so
cp -v /home/ssarkar/wesnoth-android/wesnoth-armeabi-v7a/packaging/android/lib/libmain.so /home/ssarkar/Documents/Projects/C++/wesnoth/packaging/android/app/src/main/jniLibs/armeabi-v7a/
#pushd /home/ssarkar/wesnoth-android/wesnoth-aab-base
#	mkdir manifest
#	mv AndroidManifest.xml manifest/
#	mkdir dex
#	mv classes.dex dex/
#	zip -r base.zip *
#popd
#wget -nc https://github.com/google/bundletool/releases/download/1.16.0/bundletool-all-1.16.0.jar
#BUNDLETOOL=bundletool-all-1.16.0.jar
#rm -f wesnoth-debug.aab
#java -jar $BUNDLETOOL build-bundle --modules=/home/ssarkar/wesnoth-android/wesnoth-aab-base/base.zip --output=wesnoth-debug.aab
#rm -f wesnoth-debug.apks
#java -jar $BUNDLETOOL build-apks --mode=universal --bundle=wesnoth-debug.aab --output=wesnoth-debug.apks
