name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Download dependency
      run: cd packaging/android; ./build-android-dependencies/build-android-deps.sh;

    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build
